# Generated by Django 4.2 on 2023-06-07 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username_requirement', models.BooleanField(blank=True, default=False, null=True)),
                ('pw_requirement', models.BooleanField(blank=True, default=False, null=True)),
                ('pw', models.CharField(blank=True, max_length=30, null=True)),
                ('show_answers', models.BooleanField(blank=True, default=False, null=True)),
                ('prj_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('poll_nr', models.IntegerField(default=1)),
                ('num_respondents', models.IntegerField(default=0)),
                ('num_questions', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='anonymous', max_length=150, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_batch', models.IntegerField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('num_respondents', models.IntegerField(default=0)),
                ('question_list_object', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_results', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('question_type', models.CharField(max_length=50)),
                ('answer', models.CharField(blank=True, max_length=150, null=True)),
                ('nr_choices', models.IntegerField(default=0)),
                ('option1', models.CharField(blank=True, max_length=150, null=True)),
                ('option2', models.CharField(blank=True, max_length=150, null=True)),
                ('option3', models.CharField(blank=True, max_length=150, null=True)),
                ('option4', models.CharField(blank=True, max_length=150, null=True)),
                ('option5', models.CharField(blank=True, max_length=150, null=True)),
                ('correctOptionEnabled', models.BooleanField(blank=True, default=False, null=True)),
                ('correctOption', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pjk_question', to='dashboard.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquirer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_batch', models.IntegerField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('users_answer', models.CharField(blank=True, max_length=150, null=True)),
                ('users_choice', models.IntegerField(default=0)),
                ('is_correct', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_answer', to='dashboard.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_answer', to='dashboard.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_answer', to='dashboard.respondent')),
            ],
        ),
    ]
