# Generated by Django 4.2 on 2023-05-20 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_project_pw_project_pw_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('question_type', models.CharField(max_length=50)),
                ('answer', models.CharField(blank=True, max_length=150, null=True)),
                ('nr_choices', models.IntegerField(default=0)),
                ('option1', models.CharField(blank=True, max_length=150, null=True)),
                ('option2', models.CharField(blank=True, max_length=150, null=True)),
                ('option3', models.CharField(blank=True, max_length=150, null=True)),
                ('option4', models.CharField(blank=True, max_length=150, null=True)),
                ('option5', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquirer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
