# Generated by Django 4.2 on 2023-05-20 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_project_num_questions_alter_project_user_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pjk_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
