# Generated by Django 4.2 on 2023-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_question_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctOption',
            field=models.IntegerField(default=1),
        ),
    ]
