# Generated by Django 4.2 on 2023-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_question_correctoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctOption',
            field=models.IntegerField(default=0),
        ),
    ]
