# Generated by Django 4.2 on 2023-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_question_correctoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctOptionEnabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
