# Generated by Django 4.2 on 2023-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_question_correctoptionenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_respondents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='username_requirement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
