# Generated by Django 4.2 on 2023-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_project_num_respondents_project_prj_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
