# Generated by Django 4.2 on 2023-05-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_project_prj_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
