# Generated by Django 4.2 on 2023-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_project_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
