# Generated by Django 4.2 on 2023-05-28 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_project_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poll_nr',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_batch', models.IntegerField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('users_answer', models.CharField(blank=True, max_length=150, null=True)),
                ('users_choice', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_answer', to='dashboard.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_answer', to='dashboard.question')),
            ],
        ),
    ]
