# Generated by Django 4.2 on 2023-05-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_project_poll_nr_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.IntegerField(default=0),
        ),
    ]
