# Generated by Django 4.2 on 2023-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_answers',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
