name: Sync main to deploy

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to deploy branch
        run: |
          if git show-ref --verify --quiet refs/heads/deploy; then
            git checkout deploy
          else
            git checkout -b deploy
          fi

      - name: Merge main into deploy, excluding specific files
        run: |
          git merge main --no-commit --no-ff
          # Reset the to exclude from the merge
          git reset HEAD -- Procfile runtime.txt .env.example mydb.py requirements.txt polln/settings/dev_settings.py polln/settings/prod_settings.py templates/django_reload.html
          git checkout -- Procfile runtime.txt .env.example mydb.py requirements.txt polln/settings/dev_settings.py polln/settings/prod_settings.py templates/django_reload.html
          git commit -m "Merge main into deploy, excluding specific files"

      - name: Push changes to deploy branch
        run: git push origin deploy
